backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "brand"
    label: "Brand"
    folder: "src/pages/brands"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "brand"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Logo", name: "logo", widget: "image"}
      - label: Products
        name: products
        widget: list
        fields:
          - {label: Photo, name: photo, widget: image }
          - {label: Name, name: name, widget: string}
          - {label: Sold, name: sold, widget: number, valueType: int}
          - {label: Target, name: target, widget: number, valueType: int}
          - {label: Category, name: category, widget: select, options: ["Trending", "High Profitability", "On Sale", "Missing Inventory"]}